apiVersion: v1
kind: Template
metadata:
  name: kibana
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kube-linter.io/ignore-all: "ignore the thing"
      serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"kibana"}}'
    name: kibana
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels: {}
    name: kibana
    annotations:
      kube-linter.io/ignore-all: "ignore the thing"
  spec:
    minReadySeconds: 15
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: kibana
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: kibana
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - kibana
                topologyKey: failure-domain.beta.kubernetes.io/zone
              weight: 100
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - kibana
                topologyKey: kubernetes.io/hostname
              weight: 99
        containers:
        - env:
          - name: SERVER_NAME
            value: kibana
          - name: SERVER_HOST
            value: localhost
          - name: SERVER_MAXPAYLOADBYTES
            value: '8388608'
          - name: ELASTICSEARCH_HOSTS
            valueFrom:
              secretKeyRef:
                key: endpoint
                name: kibana-elasticsearch
          - name: USER
            valueFrom:
              secretKeyRef:
                key: username
                name: admin_user_credentials
            required: false
          - name: PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: admin_user_credentials
            required: false
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: kibana
          resources:
            limits:
              cpu: 750m
              memory: 1900Mi
            requests:
              cpu: 200m
              memory: 950Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
          - --https-address=:8443
          - --provider=openshift
          - --openshift-service-account=kibana
          - --upstream=http://localhost:5601
          - --tls-cert=/etc/tls/private/tls.crt
          - --tls-key=/etc/tls/private/tls.key
          - --cookie-secret-file=/etc/proxy/secrets/session_secret
          - --pass-basic-auth=false
          image: ${OAUTH_IMAGE}:${OAUTH_IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          name: kibana-proxy
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /oauth/healthz
              port: https
              scheme: HTTPS
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /etc/proxy/secrets
            name: proxy-cookie
          - mountPath: /etc/tls/private
            name: proxy-tls
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        initContainers:
        - args:
          - -c
          - 'set -ex

            curl -XPUT "$ELASTICSEARCH_HOSTS/_template/template_1" -H ''Content-Type:
            application/json'' -d''{"template": "cwl-*","settings": {"number_of_shards": 3, "index.mapping.total_fields.limit":
            4000},"mappings": {"dynamic_templates": [{"host_tags": {"match_mapping_type":
            "string","path_match": "*host.tags.*","mapping": {"index": false}}}]}}''

            '
          command:
          - sh
          env:
          - name: ELASTICSEARCH_HOSTS
            valueFrom:
              secretKeyRef:
                key: endpoint
                name: kibana-elasticsearch
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 50m
              memory: 100Mi
          image: quay.io/app-sre/ubi8-ubi-minimal:latest
          name: es-init-template
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccountName: kibana
        terminationGracePeriodSeconds: 30
        volumes:
        - name: proxy-cookie
          secret:
            defaultMode: 420
            secretName: kibana-cookie
        - name: proxy-tls
          secret:
            defaultMode: 420
            secretName: kibana-tls
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      service.alpha.openshift.io/serving-cert-secret-name: kibana-tls
    labels:
      app: kibana
    name: kibana
  spec:
    ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      app: kibana
    sessionAffinity: None
    type: ClusterIP
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: kibana
    name: kibana
  spec:
    host: ${KIBANA_HOST}
    port:
      targetPort: 8443
    tls:
      termination: Reencrypt
    to:
      kind: Service
      name: kibana
      weight: 100
parameters:
- description: Image namespace
  name: IMAGE
  value: quay.io/cloudservices/kibana-oss
- description: Image tag
  name: IMAGE_TAG
  required: true
  value: 7.4.2
- name: OAUTH_IMAGE
  value: quay.io/openshift/origin-oauth-proxy
- name: OAUTH_IMAGE_TAG
  value: 4.4.0
- name: KIBANA_HOST
  value: kibana.apps.crc-stg-01.o4v9.p1.openshiftapps.com
