apiVersion: v1
kind: Template
metadata:
  name: p8s-elastic-exporter
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: p8s-elastic-exporter
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: p8s-elastic-exporter
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: p8s-elastic-exporter
      spec:
        containers:
        - command:
          - /bin/elasticsearch_exporter
          image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9114
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          env:
            - name: ES_URI
              valueFrom:
                secretKeyRef:
                  name: kibana-elasticsearch
                  key: endpoint
            - name: ES_ALL
              value: 'true'
            - name: WEB_LISTEN_ADDRESS
              value: ':9114'
          name: p8s-elastic-exporter
          ports:
          - containerPort: 9114
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 9114
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 64Mi
          securityContext:
            capabilities:
              drop:
              - SETPCAP
              - MKNOD
              - AUDIT_WRITE
              - CHOWN
              - NET_RAW
              - DAC_OVERRIDE
              - FOWNER
              - FSETID
              - KILL
              - SETGID
              - SETUID
              - NET_BIND_SERVICE
              - SYS_CHROOT
              - SETFCAP
            readOnlyRootFilesystem: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        imagePullSecrets:
        - name: quay-cloudservices-pull
        - name: rh-registry-pull
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: '9114'
      prometheus.io/scrape: 'true'
    labels:
      app: p8s-elastic-exporter
    name: p8s-elastic-exporter
  spec:
    ports:
    - name: 9114-tcp
      port: 9114
      protocol: TCP
      targetPort: 9114
    selector:
      app: p8s-elastic-exporter
    sessionAffinity: None
    type: ClusterIP
parameters:
- name: IMAGE
  value: quay.io/cloudservices/xjoin-es-exporter
- name: IMAGE_TAG
  value: f621527
